<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\localrefs\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="LogLibrary">
      <HintPath>..\localrefs\LogLibrary.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\localrefs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\localrefs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
	<Reference Include="websocket-sharp">
      <HintPath>..\localrefs\websocket-sharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>
</Project>